docs/around_tidal/toplap_manifesto.md
docs/innards/haskell.md
docs/innards/meaning_of_dot.md
sidebars.js

New Haskell pages:
- Meaning of dot operator.
- Haskell precisions.
New Around Tidal pages:
- TOPLAP Manifesto

Manifesto + New Haskell pages

---

docs/patternlib/tutorials/course.md
sidebars.js

Tidal Course Part I

---

docs/configuration/adding_synthesizers.md

Synthesizer tutorial

---

docs/configuration/tidal_listener.md
docs/configuration/tidal_vis.md
sidebars.js

Added a category for Tidalcycles tools (tidal-listener, tidal-vis).

New tools category

---

docs/configuration/MIDIOSC/OSC.md
docs/reference/hackage.md
sidebars.js

New "Even more" page located in the reference section (see #documentation) on the Discord chat:
- link to Hackage
- saving the old-school Perl script that was mentioned at the bottom of the page.

Even more page

---

sidebars.js

Fixing incorrect path

---

docs/getting-started/linux_install.md

This should be a bit more explicit.

Update to correct wording

---

docs/patternlib/tutorials/course1.mdx
docs/patternlib/tutorials/course2.mdx
src/components/youtube/index.jsx
src/components/youtube/styles.module.css

Added a React component for YouTube embeds. Also replaced the images on the Tidal Club class pages with embedded videos.

Add component for autosizing YouTube embeds

---

docs/getting-started/windows_install.md

windows_install - clarify cabal shell commands

---

docs/around_tidal/changelog.md
docs/configuration/MIDIOSC/MIDI.md
docs/patternlib/tour/alteration.md
docs/reference/alteration.md
docs/reference/concatenation.md
docs/reference/conditions.md
wiki-export/Controller_Input_en.md

sorry for all the deleted whitespaces on line ends - seems to be something my editor or linter does automatically when saving

add MIDI renaming, listToPat and other small updates

---

docs/reference/time.md

I'm not sure of the best way to link internally... I had a go

more accurately describe the stut ref, link to delay effect

---

docs/getting-started/windows_install.md
docusaurus.config.js

Adds powershell syntax highlighting to code blocks and fixes code blocks on Windows install page. Docusaurus doesn't appear to support code block nested in blockquotes.

Address issue #82

---

docs/patternlib/tour/conditions.md

I have added the documentation for the two functions fix and fixRange. These are conditional functions that use ControlPatterns as conditions.

Add fix and fixRange documentation

---

docs/reference/mi-ugens.md
sidebars.js

This has been sitting untouched for a while, it's about time it went in
@paulchannelstrip I could not reconcile the upstream changes after about half an hour so I just added the file to a new fork rather than dick about anymore. We lost the history, but I hope that's not an issue
We've added stub/recommended syntax for detailing the effects and synth parameters, hopefully some more interested users can help get all that written :)

add mi-ugens installation ref, credit also to paulchannelstrip

---

docs/configuration/MIDIOSC/MIDI.md
docs/configuration/Multi-User Tidal.md

As of https://github.com/tidalcycles/Tidal/pull/898, Ableton Link is used natively by Tidal. This PR updates the documentation to reflect this.

Document Link support in Tidal 1.9

---

docs/reference/time.md

Document echo and echoWith, deprecate stut and stutWith

Document echo and echoWith

---

docs/reference/conditions.md

typo (correct heading)

---

docs/configuration/Multi-User Tidal.md
docs/configuration/boottidal.md

Instructions for finding good adjustments and new explanation of configuration parameters.
Inspired by [`wiki-export/Network_tempo_sharing.md`](https://github.com/tidalcycles/tidal-doc/blob/main/wiki-export/Network_tempo_sharing.md)

Improve latency documentation

---

docs/getting-started/editor/Atom.md

Info on Atom sunsetting and plans for Pulsar

adding info about Atom sunsetting

---

docs/reference/alteration.md

minor corrections - missing elements

corrections to ply code examples

---

docs/getting-started/editor/Pulsar.md

Minor edits:
- add xattr command to fix Pulsar.app after install 
- clarify steps
- add Troubleshooting section w common errors
- minor text changes

Adjust pulsar.md

---

docs/reference/mi-ugens-installation.md
docs/reference/mi-ugens.md

Also split the installation manual to a separate page
Need to check the internal links once it goes live

add miUgens synth parameter reference

---

docs/reference/mi-ugens.md
yarn.lock

after all that testing, it failed on go-live anyway - I've tried a different format, anyone with experience here I would welcome advice :)

try to fix internal links for mi-UGens

---

docs/patternlib/tutorials/workshop.md

Resubmit of PR - this time without the wiki-export changes!
- Changed editor references to remove Atom, replace with Pulsar 
- A few grammar / wording changes
- other formatting

update workshop.md with edits

---

docs/configuration/boottidal.md
docs/getting-started/editor/Pulsar.md
docs/getting-started/macos_install.md

@ndr-brt has updated the name of the repo, the doco has several links that needed updating

update links to correct pulsar-plugin github repo

---

docs/getting-started/windows_install.md

I've made a lot of changes to windows_install.md - mostly to the Automated Installation section. This reflects recent changes in the Chocolatey package install that replaces Atom with Pulsar.  
Other changes:
- Added more detail about all the packages and components installed - to provide more transparency about what we are putting on users systems. 
- Added potential problems and fixes
- Added a Getting Help section - including directing people to Discord - Installation Help. 
- other edits throughout

Windows install edit

---

docs/getting-started/linux_install.md
docs/getting-started/windows_install.md

+ removing a double separator in the windows tutorial

Some changes to the styling in the linux install tutorial

---

blog/contributor_profile_cleary.md

Posting a blog entry for contributor profiles.

Blog profile cleary

---

docs/getting-started/linux_install.md

More consistent with other pages

Update the note styling to use tips instead

---

blog/tidal_profile_ndr_brt.md

ndr_brt tidal profile

---

docs/getting-started/windows_install.md
docs/troubleshoot/TroubleShoot_Windows.md

Add steps to resolve the Windows ghci 9.6.1 problems and network-3.1.2.8 errors.

update Windows install and troubleshooting pages

---

docs/reference/mi-ugens.md

ref: https://github.com/cleary/ansible-tidalcycles-synth-mi-ugens/pull/1 with thanks to @patrickt

update plaits to include new mode parameter

---

blog/about.md

Adding info and examples for advanced markdown options provided by Docusaurus / MDX.

adding markdown details to about.md

---

blog/blog_topic_ghostchamb3r.md

Fix <details> formating
minor edits

ghostchamb3r blog post - edits

---

blog/contributor_profile_cleary.md

I've really enjoyed going through the actual code examples people have provided in their posts, and realised I did not do that for mine... so - here's a simple one :)

add a specific code example

---

docs/configuration/adding_global_effects.md

Fixing a small typo in the global-effects docs

Fix small typo

---

blog/tidal_profile_Eloi_el_Bon_Noi.md

GitHub workflow errors on the image tags, so removing them and will try to add them later.

remove image tags

---

docs/reference/synthesizers.md

Added
- reference links for Club Tidal page and GitHub page for superfm variables
- tip on loading parameter values first
- clarified details on variable usage
- added examples

update synthesizers.md for superfm details

---

docs/reference/mi-ugens-installation.md

Tried to clarify based on installation issues noted here, https://club.tidalcycles.org/t/mi-ugens-install-issues-on-windows/4745/8

Update mi-ugens-installation.md based on feedback

---

docs/troubleshoot/TroubleShoot_Linux.md

the fix suggested in [this](https://github.com/tidalcycles/Tidal/issues/707) issue worked for me, so maybe it will help some others users too ;)

added a line to help troubleshoot jack on arch

---

docs/patternlib/tutorials/course1.mdx

Fix typo in course1.mdx

---

docs/reference/mi-ugens-plaits.md

Add chord types to Plaits

---

docs/getting-started/editor/VS_Code.md

"It is highly configurable" repeated in the next sentence.

Update VS_Code.md, remove duplicate language

---

docs/reference/mini_notation.md

Add distrib function to Euclidian Sequences section

Update mini_notation.md - add distrib function 

---

docs/reference/mini_notation.md
docs/reference/transitions.md

Added definitions for fadeIn, fadeOut, fadeInFrom, fadeOutFrom

Updated documentation for fade definitions

---

docs/showcase.md

adding rachel devorah to showcase.md

adding rd to showcase.md

---

docs/getting-started/Tutorial.md

Added clarity and example of third parameter of euclidian rhythm

---

docs/patternlib/tutorials/course1.mdx

Fixing [issue](https://github.com/tidalcycles/tidal-doc/issues/273)

Updating course 1 missing lesson and forum links
