tidalcycles/tidal-doc

docs/innards/meaning_of_dollar.md

This is a really  small change, I just noticed that the octothorp doesn't seem visible in the docs, and I think it's because of the special markdown meaning octothorps have for headers. I got this solution from https://stackoverflow.com/questions/32196555/

Make the octothorpe visible in docs

---

docs/innards/meaning_of_dollar.md

OK, sorry to contribute two commits to fix a single character in some documentation. My last solution (#46) worked in the GitHub markdown preview tab, but didn't work when rendering to HTML. I'm not sure why and I'm not going to bother figuring that part out. Using an HTML entity instead of a literal `#` seems like a clearer approach anyways.

Replace literal octothorpe with HTML entity

---

docs/index.md

add current/future funding model info
PS this patch was made following the [edit] links off the doc, and doing the editing on github directly - it works pretty nicely tbh

move ko-fi funding to past-tense, add oc info

---

docs/patternlib/tour/time.md
docs/patternlib/tutorials/effects.md
docs/patternlib/tutorials/mini_notation.md

While playing around a bit with TidalCycles I noticed some small errors and omissions in the documentation.
This Pull Request fixes the ones I found so far. Namely the following:
- Documented densityGap alias
- Fixed description in bandpass filter (the value is not the cutoff but the center frequency)
- Fixed resonance alias function of bandpass filter
- Added example for changing the probabilities with the ? in mini-notation

Fix several small issues in documentation

---

docs/getting-started/windows_install.md

moved the ``` markup to the next line, formatting it properly and allowing suitable copying of the command in the documentation

Added a needed line break to the command used

---

docs/getting-started/windows_install.md

choco install tidalcycles needs some line breaks so that the word "shell" is not seen as a syntax command
Since it is part of the markup, we add in some line breaks to format it correctly and to remove the word "shell"

added more line breaks to commands

---

docs/patternlib/tutorials/pattern_structure.md

Fix problem (hopefully) with table format when MD is converted to HTML on the Tidal Website.
Note: not sure how to test this in the full chain of events, but at least this version removes the \ escape characters that erroniously (and very confusingly) make it on to the [Tidal Web Site](http://tidalcycles.org/docs/patternlib/tutorials/pattern_structure).

Fix table format problem

---

docs/configuration/Multi-User Tidal.md

Did not prioritize this documentation adaptation in time before the other PR merge

Adapt to renaming cCyclesPerBeat -> cBeatsPerCycle

---

docs/getting-started/MacOS_installation.md
docs/getting-started/Windows_installation.md
docs/getting-started/linux_install.md
docs/getting-started/macos_install.md
docs/getting-started/windows_install.md

The old URL does not work.
By the way, is docs/getting-started/Windows_installation.md still relevant or should it be removed? It does not seem findable from navigation?

Update SuperCollider download URL

---

docs/reference/conditions.md
docs/reference/randomness.md
docs/reference/time.md

Documents whenT, contrastBy, stretch (which IMHO should be renamed in future tidal versions to avoid confusion with the stretch sampler), and inhabit
Moves stuff from conditionals and randomness to make categories make more sense. 
The "choose family" category has been moved to the randomness page.
On conditionals:
New category "conditions on control patterns" that include both fix, unfix, contrast and etc. 
New category "choosing patterns and functions" inside conditionals, related to choosing from a list of patterns or functions, for example select, selectF, etc.
The "every and the others" category has been renamed to "Conditions on cycle numbers" and now includes ifp.
The category "Boolean conditions" now only includes functions that take Pattern Bool as input.
New "Euclidians" …

Some missing functions + tidying up randomness and conditionals

---

docs/configuration/MIDIOSC/MIDI.md

Changed MIDIClockOut(device, tempoClock) to MIDIClockOut.new(deviceName, portName, tempoClock). This worked for me, the former failed on Windows and Linux.

MIDIClockOut(...) change to MIDIClockOut.new(...)

---

docs/configuration/MIDIOSC/MIDI.md

* Adds instructions for Ableton Live
* Replaces SuperCollider instructions with a class that is aware of Link quantum.
You may notice that this replaces the fix from https://github.com/tidalcycles/tidal-doc/pull/123. That fix was needed for MIDIClockOut, but not for LinkToMidiClock. I had made some local modifications to MIDIClockOut that I forgot about... Thanks for the fix in https://github.com/tidalcycles/tidal-doc/pull/123 @nicasi! Please have a look at these new instructions that should be an improvement for you.

New MIDI clock instructions

---

docs/configuration/tidal_vis.md

The old instructions were broken by tidalcycles/Tidal#649, which split up OSC configurations into targets (connection info) and shapes and removed `startMulti`. This PR updates the instructions to work with current Tidal.
It also suggests installing tidal-vis from Hackage via cabal rather than building the repo with stack, as the former worked for me where the latter failed. But this might be an issue with stack on my end; let me know if I should revert that.
If this looks good, I can make a corresponding PR for tidal-vis to update the README, which has the same instructions.

Update instructions for using tidal-vis

---

docs/reference/conditions.md

Added note on how to silence a full cycle with the every function.

update conditions.md - every func

---

docs/reference/alteration.md

As of the latest version, these functions no longer exist, so we should remove them from the docs

Remove `runWith` and `runWith'`

---

docs/getting-started/linux_install.md

Change ansible link to point directly to Cleary's GH page. Include more detail including customization options.
Add the "What's Next?" section
The Mac and Windows install pages still need work. But Linux changes are ready.

update linux install page

---

docs/getting-started/macos_install.md

The tidal-bootstrap script for macOS has been refactored. This documentation page reflects the new install script instructions with added post install steps.

Macos_install.md refactor

---

docs/getting-started/linux_install.md

I've rewritten the instructions, basically from scratch. I've also gone for the most supportable method which is via distro packaging. 
Previoiusly the recommendation was to install from source because SuperCollider was outdated (then the example SuperCollider used was 3.10).
All modern distros support 3.10.2 or higher now, and I think we should lean on repo provided packages for ease of support.
I also separated Arch and debian distro family commands, which provides a template for any other distros to be added (fedora?)

rewrite Linux instructions, allow for multi-distro command template

---

blog/about.md

The Tidal Blog info page describes the purpose of the Tidal blog and includes links to the templates and submissions instructions.

Add about.md for Tidal blog

---

docs/configuration/boottidal.md

If you do not specify the cCtrlAddr, you get an error from sendBufto.

Update documentation for how to connect to a remote SuperDirt instance

---

docs/configuration/MIDIOSC/MIDI.md

Added http:// to link url so that it wouldn't be interpreted as a relatively address.

Fix broken link in MIDI.md

---

docs/troubleshoot/TroubleShoot_Linux.md

Just noticed this small typo. It should be "runs", not run.

Fix typo in TroubleShoot_Linux.md

---

docs/configuration/boottidal.md

This PR updates `BootTidal.hs` to include the various changes made upstream since it was added to the docs in #4 (back in May 2021).
I wonder if there's a good way to make [BootTidal.hs](https://raw.githubusercontent.com/tidalcycles/pulsar-tidalcycles/master/lib/BootTidal.hs) the source of truth for the version embedded in the docs. It's already linked on the page, but the embedded snippet gets out-of-sync with the file it's referencing.
Client-side (runtime) options:
- Use JS and `fetch()`.
- Use an `<iframe>`.
Both options ensure that BootTidal will appear up-to-date, but complicate syntax highlighting and make the docs less self-contained.
Server-side (build time) options: 
- Do something custom to fetch `BootTidal.hs` at build time and inject it into `boottidal.md`.
- Use …

Update `BootTidal.hs` and use Haskell syntax highlighting

---

blog/2019-05-30-welcome.md
blog/about.md

Removed the (very outdated) welcome post from 2019 about the wiki migration. Improved the About page.

blog edits

---

docs/getting-started/Tutorial.md

Found an url pointing to the Custom Samples page not working in the tutorial, so changed it to the correct one.

Fix dead link Custom Samples

---

docs/reference/harmony_melody.md

with Tidal 1.9.5 coming up, i thought it would be good to add some documentation for [metatune](https://github.com/tidalcycles/Tidal/pull/1046).
"Harmony & Melody" seemed like the best section for it, but idk. im open to any ideas for improvement!

add documentation for metatune

---

src/components/youtube/index.jsx

Fix broken video aspect ratios

---

docs/patternlib/tutorials/workshop.md

This pull request fixes two small typos in: https://tidalcycles.org/docs/patternlib/tutorials/workshop.

docs: update tutorials/workshop.md

---

docs/reference/synthesizers.md

All the synth headings were capitalised, and did not match their name as it's used in tidal
The correct name was not mentioned as part of the usage examples, so I've just made the headings match the usage in tidal
There were also some heading size mistakes

use correct case for names of built-in synths

---

docs/configuration/MIDIOSC/MIDI.md
docs/working-with-patterns/Controller_Input.md

Noticed that the link for this script is broken. Technically it would be good to always link to the latest release version, I guess, but seeing how this pd script isn't really depending much on the inner workings of Tidal I think it's fine to just use `dev`. I checked for other links into the Tidal github repo but wasn't sure how to deal with them honestly, because they used different branches and the ones I checked still work.
PS: Ah, I think I figured out how the bad link snuck in. It uses `main` for the trunk branch, whereas other links use `master`, which is the one currently in use by the Tidal repo. I don't know if there ever was a plan to change the branch name.

Use dev branch for link to midi-osc-bridge.pd

---

docs/reference/randomness.md

Add an explanation of `markovPat` to the documentation, including an example.
This documentation is based on @kindohm's [YouTube tutorial on Markov chains](https://youtu.be/2Qj1EOEyQyk).

Add markovPat to randomness.md
